language: objective-c
osx_image: xcode7.3

env:
   global:
   - LANG=en_US.UTF-8

   - PROJECT="JSQWebViewController.xcodeproj"
   - IOS_SCHEME="JSQWebViewController"
   - IOS_SDK=iphonesimulator9.3

   matrix:
   - DESTINATION="OS=8.1,name=iPhone 4s"     SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES"  BUILD_EXAMPLE="YES" POD_LINT="YES" RUN_UI_TESTS="NO"
   - DESTINATION="OS=8.2,name=iPhone 5"      SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES"  BUILD_EXAMPLE="NO"  POD_LINT="NO"  RUN_UI_TESTS="NO"
   - DESTINATION="OS=8.3,name=iPhone 5s"     SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES"  BUILD_EXAMPLE="NO"  POD_LINT="NO"  RUN_UI_TESTS="NO"
   - DESTINATION="OS=8.4,name=iPhone 6"      SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES"  BUILD_EXAMPLE="NO"  POD_LINT="NO"  RUN_UI_TESTS="NO"

   - DESTINATION="OS=9.0,name=iPhone 5s"      SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO" RUN_UI_TESTS="YES"
   - DESTINATION="OS=9.1,name=iPhone 6s"      SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO" RUN_UI_TESTS="NO"
   - DESTINATION="OS=9.2,name=iPhone 6 Plus"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO" RUN_UI_TESTS="NO"
   - DESTINATION="OS=9.3,name=iPhone 6s Plus" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO" RUN_UI_TESTS="NO"

   - DESTINATION="OS=8.1,name=iPad 2"       SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO" RUN_UI_TESTS="NO"
   - DESTINATION="OS=8.4,name=iPad 2"       SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO" RUN_UI_TESTS="NO"
   - DESTINATION="OS=9.0,name=iPad Retina"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO" RUN_UI_TESTS="NO"
   - DESTINATION="OS=9.1,name=iPad Air"     SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO" RUN_UI_TESTS="NO"
   - DESTINATION="OS=9.2,name=iPad Air 2"   SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="NO"  POD_LINT="NO" RUN_UI_TESTS="NO"
   - DESTINATION="OS=9.3,name=iPad Pro"     SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO" RUN_UI_TESTS="NO"

script:

- if [ $POD_LINT == "YES" ]; then
      pod spec lint;
      pod lib lint;
  fi


- if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild clean build -project Example/Example.xcodeproj -scheme Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c;
  fi


- if [ $RUN_TESTS == "YES" ]; then
      xcodebuild test -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c;
  else
      xcodebuild clean build -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c;
  fi


- if [ $RUN_UI_TESTS == "YES" ]; then
      xcodebuild test -workspace JSQWebViewController.xcworkspace -scheme Example -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c;
  fi


# Build for reporting test coverage
- if [ $RUN_TESTS == "YES" ]; then
      xcodebuild test -project JSQWebViewController.xcodeproj -scheme "JSQWebViewController" -sdk iphonesimulator;
  fi

after_success:
- bash <(curl -s https://codecov.io/bash)
