osx_image: xcode7.3
language: objective-c
cache:
  - cocoapods

podfile: Example/Podfile
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install --project-directory=Example
  - pod repo update

script:
- set -o pipefail && xcodebuild test -workspace Example/Example.xcworkspace -scheme Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint --allow-warnings
